spring:
  application:
    name: crypto-trading-system
  datasource:
    url: jdbc:h2:mem:aquariux
    driverClassName: org.h2.Driver
    username: sa
    password: 12345
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

external:
  binance:
    api:
      url: 'https://api.binance.com/api/v3/ticker/bookTicker'
  huobi:
    api:
      url: 'https://api.huobi.pro/market/tickers'
